### ISSUE TITLE
Verbatim text's box is big

### ISSUE THREAD

**Issue by s1291** [scar45/ResponsivePivot#1]
The verbatim text written in Zim when rendered using this template is relatively very big when the text is inline.
Here is a screenshot of the text in Zim:

![02](https://user-images.githubusercontent.com/17838489/32692167-7d270696-c713-11e7-8bc9-261e2a40cbdc.png)

And here is the result:
![01](https://user-images.githubusercontent.com/17838489/32692172-9151343e-c713-11e7-8370-951a9e7df501.png)

**Comment by scar45** [comment]
Thank you for calling this out. The padding on these elements was certainly overkill. Here's what I've adjusted it to be:

![image](https://user-images.githubusercontent.com/262645/33359183-64b99d72-d49b-11e7-9d7f-460c1d8de1cd.png)

Hopefully this helps -- thanks again!

**Comment by scar45** [comment]
Actually, just realized that the coloured border is unnecessary, but I left the CSS in if you (or anyone for that matter) wanted to re-enable it. Latest (and final!) version preview:

![image](https://user-images.githubusercontent.com/262645/33359304-06e51e64-d49c-11e7-80ee-a82373b54749.png)
